source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'Promissum', :path => '../'

target :PromissumExtensionsTests do
  # This Pods library links with a target in another project.
  xcodeproj 'PromissumExtensions'
end
