source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'CoreDataKit', :git => 'https://github.com/tomlokhorst/CoreDataKit.git', :branch => 'feature/swift2'
pod 'Promissum', :path => '../'

target :PromissumExtensionsTests do
  # This Pods library links with a target in another project.
  xcodeproj 'PromissumExtensions'
end
