platform :ios, '9.0'
use_frameworks!

# xcodeproj "PromissumExtensions.xcodeproj"
# link_with "PromissumExtensions", "PromissumExtensionsTests"

pod 'Alamofire', '~> 4.0'
pod 'CoreDataKit', '~> 0.12'
# pod 'Promissum', :path => '../' # All Promissum source files are manually included in project

target 'PromissumExtensions'
target 'PromissumExtensionsTests'

