source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'CoreDataKit', '~> 0.9'
pod 'Promissum', :path => '../../'
pod 'Promissum/Alamofire', :path => '../../'
pod 'Promissum/CoreDataKit', :path => '../../'
pod 'Promissum/UIKit', :path => '../../'
