platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 4.0'
pod 'CoreDataKit', :git => 'https://github.com/mac-cain13/CoreDataKit.git', :branch => 'swift3'
pod 'Promissum', :path => '../../'
pod 'Promissum/Alamofire', :path => '../../'
pod 'Promissum/CoreDataKit', :path => '../../'
pod 'Promissum/UIKit', :path => '../../'

target 'FadeExample'
