source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'Promissum', :path => '../../'
pod 'Promissum/Alamofire', :path => '../../'
